[package]
name = "fsdaemon"
version = "0.1.0"
edition = "2021"

[dependencies]
fuser = "0.14"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
libc = "0.2"